class Credit extends Phaser.Scene{
    constructor(){
        super('creditScene')
    }

    preload(){

    }

    create(){

        //credit config
        let creditConfig = {
            fontFamily: 'Courier New',
            fontSize: '30px',
            // backgroundColor: '#F3B141',
            backgroundColor: '#000000',
            color: '#FFFFFF',
            align: 'right',
            padding: {
                top: 5,
                bottom: 5,
            },
            fixedWidth: 0
        }

        this.select = this.sound.add('select', {volume: 0.2})
        keyLEFT = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.LEFT)

        let credit = this.add.text(this.game.config.width / 2, this.game.config.height /2, 
        'Credits:\n\n Background Music used from Pixabay: https://pixabay.com/music/modern-classical-relaxing-145038/\n\n All sound effects used can be found on Pixabay\n\n Title font on Menu generated by Text Studio: https://www.textstudio.com/logo/super-mario-599\n\n Artwork for background and sprites done by Mohammad Taquie using Aseprite\n\n Programming done by Mohammad Taquie\n\n',{
            fontFamily: 'Times New Roman',
            fontSize: '25px',
            color: '#FFFFFF',
            backgroundColor: '#000000',
        }).setOrigin(0.5)
        
        
        this.add.text(game.config.width/2, game.config.height/1.2, 'Press "<-" to go back to the menu', creditConfig).setOrigin(0.5);

    }

    update(){
        if (Phaser.Input.Keyboard.JustDown(keyLEFT)){
            this.select.play()
            this.scene.start('menuScene')

        }

    }


}